### ISSUE TITLE
Possible to draw Bezeir Curve path 

### ISSUE THREAD

**Issue by deltamish** [yasirkula/UnityBezierSolution#1]
I just downloaded your tool and i love it. Amazing work man 

In the doc you have mention DrawGizmos command . when checked it draws the linear path. Is it possible to draw the bezier curve instead ? 

thanks

**Comment by deltamish** [comment]
Lol Never mind. I just had to adjust the smoothness. Was in a hurry so my mind completely skipped it 

Thanks for the amazing tool btw

**Comment by yasirkula** [comment]
Hey, thank you :)
