### ISSUE TITLE
Convert to upm package directory structure

### ISSUE THREAD

**Issue by favoyang** [yasirkula/UnityBezierSolution#10]
Hi @yasirkula ,

Thanks for making the unity open source project. I'd like to add this to [OpenUPM](https://openupm.com) a public upm registry with automatic build pipelines, that publish semver git tags to upm packages.  You can read [the announcement](https://www.patreon.com/posts/openupm-beta-is-32544176) to get the basic idea, so far it hosts 90+ packages as of December 2019.

I've noticed that you have a series popular unity projects , can be convert to [upm package](https://docs.unity3d.com/Manual/cus-layout.html). So I'd like to work with you on this project, to figure out a best way to convert you projects. There're many ways to convert a project
- Option 1: pure upm package, where package.json is located at root path.
- Option 2: unity project + upm package, where upm package is located at `Packages/<your-package-name>`, as a local upm package. So you can develop and test the package without creating another unity project.
- Option 3: based on option2, use `git subtree` to create a upm branch from `Packages/<your-package-name>` where package.json is placed at root path.

In https://github.com/yasirkula/UnityBezierSolution/pull/9, I implemented option 2.
- I created a local package at Packages/<your-package-name>
  - add `package.json`
  - move your scripts to `Packages/<your-package-name>/Runtime`, add a script asmdef  file.
  - move your editor scripts to `Packages/<your-package-name>/Editor`, add an editor asmdef file (reference the script asmdef file)
  - leave the sample scene to Assets/ folder. It should/can be moved to `Packages/<your-package-name>/Samples~/<sample-name>`. But it's not convenience enough to keep develop the sample. As the folder with `~` suffix are not imported to Unity by default. It's something the openupm build pipelines can take care for you in a smart way.

Since moving directory structure is usually something sensitive, feel free to start a conversation with me on pros/cons, or figure out a better approach.

After the conversion, a few todos to make it useful
- Implement the option 3 by creating a clean upm branch
- Create GitHub release based on semantic versioning (x.y.z)
- Add the package to openupm and add badge optional

**Comment by yasirkula** [comment]
Thank you for the detailed documentation and the PR. I want my repositories to have the same folder structure with their Asset Store counterparts. So options 2 and 3 are not viable solutions for me. If I follow option 1, then the redundant files and folders at the root directory like Images, LICENSE, README.md will also be included in the package. I'd like to skip this opportunity for now but thanks again for the suggestion.

**Comment by favoyang** [comment]
Thanks for the claim. It totally makes sense to keep the data structure to support existing users on the Asset Store. I'll bring you another simple approach later then as option 4. I need do some tests, stay tuned and happy new year.

**Comment by favoyang** [comment]
Option 4: keep the directory structure no change, by using the `Assets/Plugins/BezierSolution` as the root of package. Just adding 3 major files (and 3 `.meta` files).
- adding package.json to `Assets/Plugins/BezierSolution/package.json`
- adding `Assets/Plugins/BezierSolution/net.yasirkula.unitybeziersolution.asmdef`
- adding `Assets/Plugins/BezierSolution/Editor/net.yasirkula.unitybeziersolution.Editor.asmdef` which references the `net.yasirkula.unitybeziersolution.asmdef`

That's it, the benefits
- Leave the existing directory structure no change.
- Scripts under `Assets/Plugins/BezierSolution/`, `Assets/Plugins/BezierSolution/Editor/` are compiled into separate managed assemblies. This will not affect asset store user, because the whole `BezierSolution` folder was placed under Plugins folder, which is a special folder compiled into a separate managed assembly already.
- The UPM package directory structure is equals to the asset store release.
- OpenUPM build bot can locate any folder with a `package.json` as the package root, to do the package publish job.
- It gives you the option to `git subtree` the `Assets/Plugins/BezierSolution` folder to a clean upm branch (to be able to install via git url).

Why it works (the details)?
- The option 2 is based on the suggested [package layout](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html), but it is only a convention. Because Unity intros the upm thing after the asset store, which already have a large assets base. They realize that it takes years to convince asset author to convert to new format. So it designed a very loosely system,
  - must have a `package.json` file at the root path.
  - must have a `.asmdef` file to turn the package scripts into a separate managed assembly.
  - must have an editor `.asmdef` file to turn the package editor scripts into a separate managed assembly.
  - package layout is a convention rather than a requirement.

Will this and pull request https://github.com/yasirkula/UnityBezierSolution/pull/11 satisfy you?

**Comment by yasirkula** [comment]
This is definitely better, **your consistent help is appreciated**. I don't think I'll be supporting upm anytime soon, though. Even this 4th option requires three additional files (two .asmdef and one package.json) added to the plugin's source files (I want the contents of Plugins/BezierSolution folder to be a 1-to-1 copy of the Asset Store version) and frankly, for the time being, I'm happy with distributing my assets via Asset Store and *.unitypackage*s. As time passes, I might also switch over to upm but I don't think it will happen now.

**Comment by favoyang** [comment]
Sorry to hear that, but I understood and I respected your decision. 

Well at least the new adding files are harmless in technique. It's okay to submit those files to asset store in the future, to achieve your `1-to-1 copy` intention.

You're really a star in the Unity open source community, contributing many quality unity plugins. You must notice that using upm packages have many benefits over the asset store. Dependency and version managements for example, are in general good practices of software development for decades. Even Unity has [a longer plan](https://forum.unity.com/threads/plans-for-assetstore-packages.652297) to fuse the asset store with package manager.

BTW, on the OpenUPM platform, there're many examples of maintainer published forked open source project, because the original author don't have time or don't want to maintain an upm package at the moment. i.e. turns those nuget packages to upm format. But convince the original author is still my first choice for less maintain work, and also grow the community.

Anyway, I've made my points and let me know if you change your mind to give upm a second chance.

**Comment by yasirkula** [comment]
Added Package Manager support with the latest release. I'm hoping that it is also compatible with OpenUPM now :)

**Comment by favoyang** [comment]
@yasirkula That's really awesome. Would you mind create a new GitHub release (1.27.0 or bump version to 1.27.1) from the master branch? So the OpenUPM will track new Git tags to publish a release. Then I will retire my fork to switch to this original repository.

**Comment by yasirkula** [comment]
Released 1.27.1, hope it works now.

**Comment by favoyang** [comment]
Hi @yasirkula,

The forked repo is retired, you can visit your package at 
https://openupm.com/packages/com.yasirkula.beziersolution/

Thanks for your contribution.

**Comment by favoyang** [comment]
There are currently some broken images on the [package detail page](https://openupm.com/packages/com.yasirkula.beziersolution/), caused by the unusual README.md path, which usually located at the root path, but in your case located at `.github/` folder.

It will be fixed with https://github.com/openupm/openupm/issues/91, but not my current focus, so may take a while.

**Comment by yasirkula** [comment]
Thanks for letting me know. I've seen this usage on the [Deform](https://github.com/keenanwoodall/Deform) repository and quite liked it since it hides README.md from Unity but still keeps it visible on GitHub.

**Comment by favoyang** [comment]
Hi @yasirkula, JFYI that the broken image links have been fixed, as part of [openupm#91](https://github.com/openupm/openupm/issues/91).
https://openupm.com/packages/com.yasirkula.beziersolution/

**Comment by yasirkula** [comment]
Looks awesome! I've received your last e-mail but didn't get a chance to create new releases for my repos yet (I publish a unitypackage with each release). Will do as soon as possible.

**Comment by yasirkula** [comment]
@favoyang I was thinking about adding the OpenUPM installation instruction to all my repositories while also creating new releases for them. I'd like to ask you a couple of questions, though:

- will OpenUPM urls be the same as the package name defined inside _package.json_, i.e. the [AdjustPivot](https://github.com/yasirkula/UnityAdjustPivot/blob/master/package.json) repository's package name is com.yasirkula.adjustpivot, so will OpenUPM url be `openupm add com.yasirkula.adjustpivot`?
- will OpenUPM discover these repositories after creating a new release? If not, it'd be bad to include an OpenUPM instruction that didn't work for that repository (all the repositories have the same layout as this UnityBezierSolution repo)

**Comment by favoyang** [comment]
Cool.

> * will OpenUPM urls be the same as the package name defined inside _package.json_, i.e. the [AdjustPivot](https://github.com/yasirkula/UnityAdjustPivot/blob/master/package.json) repository's package name is com.yasirkula.adjustpivot, so will OpenUPM url be `openupm add com.yasirkula.adjustpivot`?

Yes. The install command will be `openupm add <package-name>`, and the detail page URL will be `https://openupm.com/packages/<package-name>/`

> * will OpenUPM discover these repositories after creating a new release? If not, it'd be bad to include an OpenUPM instruction that didn't work for that repository (all the repositories have the same layout as this UnityBezierSolution repo)

- The package needs to be submitted manually first - https://openupm.com/packages/add/. You can submit on your own, or if you have a list of repositories to process, I can help you submit them, then inform you later.
- Then every 5 minutes our pipelines scan your valid Git tags to bundle new releases.
- The README fetch is slightly behind but will keep sync with your repository.

**Comment by yasirkula** [comment]
I've created new releases and added OpenUPM instructions for the following repositories:

https://github.com/yasirkula/Unity360ScreenshotCapture
https://github.com/yasirkula/UnityAdjustPivot
https://github.com/yasirkula/UnityAndroidRuntimePermissions
https://github.com/yasirkula/UnityAssetUsageDetector
https://github.com/yasirkula/UnityDynamicPanels
https://github.com/yasirkula/UnityGridFramework
https://github.com/yasirkula/UnityImageCropper
https://github.com/yasirkula/UnityIngameDebugConsole
https://github.com/yasirkula/UnityInspectPlus
https://github.com/yasirkula/UnityNativeCamera
https://github.com/yasirkula/UnityNativeGallery
https://github.com/yasirkula/UnityNativeShare
https://github.com/yasirkula/UnityRuntimeInspector
https://github.com/yasirkula/UnityRuntimePreviewGenerator
https://github.com/yasirkula/UnityRuntimeSceneGizmo
https://github.com/yasirkula/UnityRuntimeTexture
https://github.com/yasirkula/UnitySimpleFileBrowser
https://github.com/yasirkula/UnitySimpleGDPRConsent
https://github.com/yasirkula/UnitySimpleInput
https://github.com/yasirkula/UnityTextureOps

I'd appreciate it if you could help me submit these repositories to OpenUPM. Thank you 😄

**Comment by favoyang** [comment]
My pleasure. You can find all your packages from [a package page](https://openupm.com/packages/com.yasirkula.simpleinput/)'s sidebar. It is aggregated by your scope (e.g. com.company). The author's profile page is also under consideration.

![image](https://user-images.githubusercontent.com/125390/82014078-67501980-96ae-11ea-8be3-be7a317d217c.png)
