### ISSUE TITLE
Increase line size

### ISSUE THREAD

**Issue by IcantThinkOfAnymoreNames** [yasirkula/UnityBezierSolution#12]
GameObject > Bezier Spline creates a curved line. I can change the line's color and make it display when the game is running. How do I make the line thicker? How do I attach a textured tube to the line, so that the tube turns with the line?

**Comment by yasirkula** [comment]
To have complete control over the line, you can use a LineRenderer and use this script to synchronize it with the spline: https://forum.unity.com/threads/bezier-solution-open-source.440742/#post-3699367

To have an actual 3D mesh follow the spline, you'll have to create a procedural mesh. This will require some scripting knowledge. You can use the same script in the provided forum post to fetch the center points of the tube. To get the points on the perimeter of the tube, for each center point, you can get points perpendicular to that center point's tangent value that is returned by spline.GetTangent.
