### ISSUE TITLE
Bezier walker from middle of spline

### ISSUE THREAD

**Issue by kobi666** [yasirkula/UnityBezierSolution#16]
not really an issue, just wondering if that capability is coming,
or if you have a tip on how to create a walker that starts walking in some arbitrary point in the spline.
if this is rude of me to ask this here (didn't find any other place to do so) 
please delete and i'll forever be in shame :)

**Comment by yasirkula** [comment]
If setting walker's NormalizedT to 0.5 doesn't put it to the exact middle point that you want, you can try the following code:

```csharp
float t = 0f;
walker.Spline.MoveAlongSpline( ref t, walker.Spline.GetLengthApproximately( 0f, 1f, 50 ) * 0.5f, 3 );
walker.NormalizedT = t;
```

You can increase the 50 and 3 parameters to make it more accurate.

**Comment by kobi666** [comment]
OMG you are amazing thank you!!!!!!!!!!
