### ISSUE TITLE
Look at something when the camera moves

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityBezierSolution#17]
![image](https://user-images.githubusercontent.com/50401776/94506459-0598e200-0240-11eb-8e0b-16adbd702b0d.png)
![image](https://user-images.githubusercontent.com/50401776/94506654-7b04b280-0240-11eb-8df5-ee2097de3c73.png)
I tried many times but never realized

**Comment by yasirkula** [comment]
You can set BezierWalker's **Look At** mode to **None** and use `transform.LookAt` in your script's Update function, or set BezierWalker's Look At mode to **Spline Extra Data** (see [video tutorial](https://www.youtube.com/watch?v=OpniwcFwSY8)).

**Comment by ShenKang4181** [comment]
I have watched this video, it is very simple, thank you, I have learned it, love you
