### ISSUE TITLE
Reset of a spline doesn't remove all the points

### ISSUE THREAD

**Issue by aprouzeau** [yasirkula/UnityBezierSolution#2]
Hi,

When I tried to reset the spline by using "Initialize" with a number of points lower than the previous spline, it didn't remove all the previous points and I ended up with too much point.

I had to manually remove of add the appropriate number of points:
```c#
if(spline.Count > newRendPoint.Length)
{
    for(int i= prevLength-1; i>= newRendPoint.Length; i--)
    {
        spline.RemovePointAt(i);
    }
}
else if(spline.Count < newRendPoint.Length)
{
    for (int i = prevLength; i < newRendPoint.Length; i++)
    {
        spline.InsertNewPointAt(i);
    }
}
```

**Comment by yasirkula** [comment]
https://github.com/yasirkula/UnityBezierSolution/commit/72e83c769a4c684c7908a49cf4f5832d1bcc631d should resolve this issue.

**Comment by yasirkula** [comment]
Now the update is live on Asset Store, as well.
