### ISSUE TITLE
How to create 2 bezier paths with 2 independent runs with BezierWalkerWithSpeed

### ISSUE THREAD

**Issue by skyprotect** [yasirkula/UnityBezierSolution#20]
I have a project, need to create many bezier lines, each object will move independently on the bezier line using the BezierWalkerWithSpeed function. how can i control moving objects on different bezier lines with different motion start time and motion speed. Thank you

**Comment by yasirkula** [comment]
Each object will have its own BezierWalkerWithSpeed component. Then you can assign different splines, speeds and normalized T's to these components.

**Comment by skyprotect** [comment]
thank you!
