### ISSUE TITLE
determine the position of the points on the curve

### ISSUE THREAD

**Issue by skyprotect** [yasirkula/UnityBezierSolution#24]
Hi bro!
i have a bezier line made up of a number of points. An object moves on that bezier with bezierWalkerWithSpeed. how to determine the position of a point on that bezier line after a certain time with a given speed. For example, a car moving on the road with a speed of 40km/h. I can locate that car every 1 minute before that car moves. Thank you!

**Comment by skyprotect** [comment]
i have speed of object.  i get length of spline with GetLengthApproximately and then i get time object move to end of spline. get Length object move in 30 second. finally i get position of point in 30second by GetPoint.  with line is straight line, that is correct. but with line is bezier spline, the position of point not correct

**Comment by yasirkula** [comment]
**BezierWalkerWithSpeed** uses _MoveAlongSpline_ function which is not a pinpoint-accurate function, it can deviate from expected results after a while (but visually, it looks like the object is indeed moving at constant speed).

How about using **BezierWalkerWithTime** with **High Quality** option enabled? It should also move along the spline at constant speed but here, you aren't specifying the speed but rather the travel time. You can calculate the travel time from your script like this: `walker.travelTime = walker.spline.evenlySpacedPoints.splineLength / desiredSpeed;`. This movement method should be very accurate.

To get the position of the object in the future, you can use the following code:

```csharp
float currentPercentage = walker.spline.evenlySpacedPoints.GetPercentageAtNormalizedT( walker.NormalizedT );
float futureNormalizedT = walker.spline.evenlySpacedPoints.GetNormalizedTAtPercentage( currentPercentage + desiredDistance / walker.spline.evenlySpacedPoints.splineLength );
Vector3 futurePoint = walker.spline.GetPoint( futureNormalizedT );
```

**Comment by skyprotect** [comment]
Thanks for your support! 
But there's one thing I can't understand. When I use BezierWalkerWithTime with High Quality. The position of the future object is incorrect. When I set High Quality to false, the location is correct. But it doesn't matter anymore. Thanks to you I solved my problem. thank you so much!

**Comment by yasirkula** [comment]
Theoretically, future object position shouldn't be incorrect. How did you estimate that it was incorrect?

**Comment by skyprotect** [comment]
at runtime, I initialize the sphere at each position that I define in the future on the bezier line. then i turn on **high quality** mode for moving object on bezier. after 30 seconds the object doesn't get to the correct sphere position I initialized earlier. Where I turn off **high quality** mode, after exactly 30 seconds the object moves to the correct sphere

**Comment by yasirkula** [comment]
You need to place your spheres like this: `sphere.position = spline.GetPoint( spline.evenlySpacedPoints.GetPercentageAtNormalizedT( NormalizedT ) );`

**Comment by skyprotect** [comment]
@yasirkula : hi bro.I think the problem is still not solved. you can see this image [https://im.ge/i/FfW7y](url) Predicting the next point over time is still not accurate. because the distances between the points are not equal.
My method is:
- get Length of spline: `spline[0].evenlySpacedPoints.splineLength`
- Set TravelTime with with preset speed: `gameObject.GetComponent<BezierWalkerWithTime>().travelTime = S/speed`
- Get the location of Points every 30 seconds in the future: I divided 30 seconds by the total travel time to get the NormalizedT and GetPoint from it
` for (int j = 1; j <= PointNumber; j++)
                {
                    Point30[j] = new Vector2(spline[0].GetPoint((j * 30f) /TraverTime).x, spline[0].GetPoint((j * 30f) / TraverTime).z);}`
- And Then i place my spheres in:
`  Instantiate(Point, new Vector3(Point30[j].x, 2.5f, Point30[j].y), transform.rotation);`
you can see the image behind. The motion of the object to each sphere takes exactly 30 seconds. in the picture above, the object takes 1 minute to reach the 2nd sphere. but the distances between the spheres are not equal

**Comment by yasirkula** [comment]
You still aren't using the method I've posted in my previous post. `GetPoint(GetNormalizedTAtPercentage(t))` will return uniformly spaced points. `GetPoint(t)` never will.

**Comment by skyprotect** [comment]
thank you for your support! My English is not good and my coding skills too the problem is solved

**Comment by yasirkula** [comment]
No problem. Don't hesitate to reopen the issue if you get stuck.
