### ISSUE TITLE
Z axis position of points set to 15.05005 When moved in Quick Edit mode.

### ISSUE THREAD

**Issue by Miredly** [yasirkula/UnityBezierSolution#26]
**Description of the bug**

When working in Quick Edit mode with Unity's editor window set to 2D, the Z axis position of any point that is selected is set to 15.05005

**Reproduction steps**

1) Set Unity Editor to 2D
2) Create a new BezierSpline game object.
3) Enter Quick Edit mode in the inspector.
4) Click on points in the editor window and move them around.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2020.3.27f1
- Platform: Editor, MacOS.
- Device: N/A
- How did you download the plugin: OpenUPM, have verified plugin version is 2.3.0, latest release at time of writing.

**Additional info**

No error messages to provide.

**Comment by yasirkula** [comment]
For the time being, Quick Edit mode tries to snap the points to the scene geometry and as a fallback, it returns a point 5 units away from the Scene camera. Until I come up with an alternative solution, you'll need to modify the source code:

https://github.com/yasirkula/UnityBezierSolution/blob/6e4e8efd087ea4b5aed814f44c051b34e7399491/Plugins/BezierSolution/Editor/BezierUtils.cs#L565

You can simply preserve the Z position here.
