### ISSUE TITLE
PrefabStage and PrefabStageUtility compile errors on 2020.3 and earlier

### ISSUE THREAD

**Issue by EvgeniyErzutov** [yasirkula/UnityBezierSolution#28]
In Unity 2020.3 and earlier PrefabStage and PrefabStageUtility are in experimental namespace and cause a couple of compilation errors. 

https://docs.unity3d.com/2020.3/Documentation/ScriptReference/Experimental.SceneManagement.PrefabStage.html

https://docs.unity3d.com/2020.3/Documentation/ScriptReference/Experimental.SceneManagement.PrefabStageUtility.html

![image](https://user-images.githubusercontent.com/102229745/160592175-2a011652-c0f3-43ec-a53f-7b634ab5931b.png)

**Comment by yasirkula** [comment]
I'll prioritize this issue, thanks!

**Comment by yasirkula** [comment]
Fixed in https://github.com/yasirkula/UnityBezierSolution/commit/472ab84d050b19a57a449793770fd43902a35954
