### ISSUE TITLE
need help!

### ISSUE THREAD

**Issue by skyprotect** [yasirkula/UnityBezierSolution#5]
hi friend!
how can i show bezier line in runtime? thank!
![Untitled](https://user-images.githubusercontent.com/26605042/63236869-aa897300-c269-11e9-8e56-cc1e804ccb04.jpg)

**Comment by yasirkula** [comment]
Of course! Try enabling "Draw Runtime Gizmos" from the bezier spline's Inspector. You can tweak the color and the smoothness of the curve by calling the spline's `DrawGizmos` function from your script (it is sufficient to call this function only once).

**Comment by skyprotect** [comment]
Thank you for the help! sorry if i'm wrong, but i think gizmos is not bezier. When I turn on Draw Gizmos Runtime, the blue line appears. It is not a bezier. So I found your answer in the solidarity forum and I created the pink bezier line. Thank you
![Zalo_ScreenShot_20_8_2019_223562](https://user-images.githubusercontent.com/26605042/63312629-54313880-c32c-11e9-8619-3c04283558c2.png)

**Comment by yasirkula** [comment]
Glad it is working. Just letting you know that smoothness of the blue spline can be adjusted via the Scripting API (DrawGizmos function).
