### ISSUE TITLE
Question on "fake" gravity.

### ISSUE THREAD

**Issue by fatboxSoftware** [yasirkula/UnityBezierSolution#7]
Not really an issue, everything works perfectly (thank you for such and awesome spline solution). I do however have a question. Where should I look in the code to implement a fake gravity along a spline? For example a spline that has (3) points, a left and right point that sit higher up than a center point. I'd like the object to "roll" down from either of the left or right points down to the center point.

**Comment by yasirkula** [comment]
Do you mean like changing the BezierWalkerWithSpeed component so that it is affected by the points' y-position differences and accelerates/decelerates accordingly?

**Comment by fatboxSoftware** [comment]
That may work. I am moving the object along the spline using keyboard input and that works well. However I'd like the object to roll back to the lowest Y point in the spline gradually when I'm not providing input via the keyboard.

**Comment by yasirkula** [comment]
This component has given me acceptable results:

```csharp
using UnityEngine;
using BezierSolution;

public class BezierWalkerWithGravity : MonoBehaviour
{
	public BezierWalkerWithSpeed bezierWalker;

	public float speed = 3f;
	public float drag = 1f;
	public float slopeThreshold = 0f;

	private void Update()
	{
		float walkerSpeed = bezierWalker.speed;
		float input = Input.GetAxisRaw( "Horizontal" );
		if( input != 0f )
			walkerSpeed = Mathf.Lerp( walkerSpeed, input * speed, 10f * Time.deltaTime );
		else
		{
			float slope = bezierWalker.Spline.GetTangent( bezierWalker.NormalizedT ).y;
			if( !bezierWalker.MovingForward )
				slope = -slope;

			if( Mathf.Abs( slope ) > slopeThreshold ) // Slope is in range [-1,1]
			{
				float slopeForce = Mathf.Abs( slope * Physics.gravity.y * Time.deltaTime );
				float walkerSpeedSign = walkerSpeed > 0f ? 1f : -1f;
				if( slope < 0f )
					walkerSpeed += walkerSpeedSign * slopeForce;
				else
					walkerSpeed -= walkerSpeedSign * slopeForce;
			}

			float dragForce = drag * Time.deltaTime;
			if( walkerSpeed >= 0f )
			{
				if( walkerSpeed <= dragForce )
					walkerSpeed = 0f;
				else
					walkerSpeed -= dragForce;
			}
			else
			{
				if( walkerSpeed >= -dragForce )
					walkerSpeed = 0f;
				else
					walkerSpeed += dragForce;
			}
		}

		bezierWalker.speed = walkerSpeed;
	}
}
```
