### ISSUE TITLE
How to stop

### ISSUE THREAD

**Issue by skyprotect** [yasirkula/UnityBezierSolution#8]
Hi friend! Thank you so much for your support.  I have a new problem.  Can you help me!
  I have an aircraft.  It moves on bezier line.  How can I destroy an aircraft, and make it fall to the ground as it moves in the bezier line.
means the aircraft will stop moving on the bezier line, and fall to the ground according to the physical nature of the unity. Sorry for my english!

**Comment by yasirkula** [comment]
You can simply disable the Bezier Walker component and enable the Rigidbody by setting its "Is Kinematic" to false (if there is no Rigidbody on the plane, add one and set its "Is Kinematic" to true). There is one catch, though: the plane will not keep its velocity, it will simply fall down without any forward momentum. You'll have to use a workaround like this:

```csharp
public void Fall()
{
	bezierWalker.enabled = false;
	rigidbodyComponent.isKinematic = false;
	rigidbodyComponent.velocity = bezierWalker.Spline.GetTangent( bezierWalker.NormalizedT ) * 2.5f; // changing 2.5 will adjust the forward momentum
}
```
